---
# Configuration file defining biological data to retrieve and install.
# These are stored in an Amazon S3 bucket:
# https://s3.amazonaws.com/biodata
# and retrieved using the data_fabfile Fabric script.

# ## Genome data -- Next generation sequencing and Galaxy

# Details about the genomes you want to include.
#  Required genome fields (corresponding to Galaxy's tool_data_table_conf.xml columns):
#    dbkey   - globally unique identifier for the genome (e.g., hg19)
#    name    - descriptive name for the given genome (to be displayed in Galaxy, e.g., Hsapiens)
#  Optional genome fields (corresponding to Galaxy's tool_data_table_conf.xml columns):
#    formats, species, dbkey1, dbkey2, value, path, index
#  Additional genome fields specific to data deployment:
#    genome_indexes - list of tool indexes specific to the associated genome (overrides global 'genome_indexes')
genomes:
  - dbkey: phix
    name: phiX174
  - dbkey: hg19
    name: Human (hg19)
    dbsnp: true
    rnaseq: true
    annotations: [battenberg]
  - dbkey: GRCh37
    name: Human (GRCh37)
    dbsnp: true
    rnaseq: true
    annotations: [battenberg]
  - dbkey: hg38
    name: Human (hg38) full
    annotations: [dbsnp, clinvar, mills_indels, 1000g_snps, 1000g_indels, 1000g_omni_snps, hapmap_snps]
  - dbkey: hg38-noalt
    name: Human (hg38) without alternative alleles
    annotations: [dbsnp, clinvar, mills_indels, 1000g_snps, 1000g_indels, 1000g_omni_snps, hapmap_snps]
  - dbkey: mm9
    name: Mouse (mm9)
    dbsnp: true
    rnaseq: true
  - dbkey: mm10
    name: Mouse (mm10)
    dbsnp: true
    rnaseq: true
  - dbkey: rn5
    name: Rat (rn5)
    rnaseq: true
  - dbkey: canFam3
    name: Dog (canFam3)
    dbsnp: true
    rnaseq: true
  - dbkey: dm3
    name: D melangogaster (dm3)
  - dbkey: TAIR10
    name: Arabidopsis thaliana (TAIR10)
  - dbkey: xenTro3
    name: X tropicalis (xenTro3)
  - dbkey: Zv9
    name: Zebrafish (Zv9)
  - dbkey: sacCer3
    name: S cerevisiae (sacCer3)
  - dbkey: WBcel235
    name: C elegans (WBcel235)
  - dbkey: pseudomonas_aeruginosa_ucbpp_pa14
    name: Pseudomonas aeruginosa UCBPP-PA14

# Global set of indexes to include for each genome.
# Available choices are in GENOMES_INDEXES_SUPPORTED in cloudbio/biodata/genomes.py
genome_indexes:
  - bowtie2
  - bwa
  - novoalign
  - ucsc

# Additional data targets
install_liftover: true
install_uniref: false
